### ISSUE TITLE
Is there official comparison of Yew and Sauron

### ISSUE THREAD

**Issue by vi** [ivanceras/sauron#10]
They both have similar goals and both are inspired by Elm. So what's the difference?

I think Sauron's README should mention Yew explicitly and include some table outlining similarities and differences.

**Comment by ivanceras** [comment]
The main difference is the syntax. 

## Syntax wise:
- **Sauron** code is  a lot shorter compared to **yew**. 
        - no need for  `type Message = Msg;`,  `type Properties = ();`, `fn change()`
- **Sauron** is a lot closer to `elm` than **yew** to `elm` 
    - usage of `Cmd` on `init` and `update`, where elm just return true or false
- minimal use of macros, in accordance with `elm` where the view are just function calls rather than separate syntax.

## Goal
- Sauron's goal is to provide simple interfaces
       - evident in fetch data example, the user don't have to manually write http request callbacks.
- Extensibility, sauron core architecture is extensible. 
       - I was able to extend sauron to be use in [native GUI client](https://github.com/ivanceras/sauron-native)

**Comment by vi** [comment]
Something like this should be near README.
