### ISSUE TITLE
input disabled attribute had different behavior that I was expecting in node macro

### ISSUE THREAD

**Issue by deathbreakfast** [ivanceras/sauron#42]
I was playing around with some of the examples and was trying to use the macro opposed to the core library functions.

When attempting to update the buttons in the [fetch-data](https://github.com/ivanceras/sauron/blob/8d41cd53e88752be4e6825219a69550eccdb87fd/examples/fetch-data/src/lib.rs) example I noticed that the disabled attribute was not working as I expected.

```
<input 
  class="prev_page" 
  type="button" 
  disabled={self.page <= 1}
  value="<< Prev Page"
    on_click=|_| {
    trace!("button is clicked");
    Msg::PrevPage
  }
/>
```

After expanding and digging into the code I found that we are just passing the attribute and value directly though. Since the HTML behavior is only check if the attribute is present this makes sense.

It would be nice to see the macro have the same behavior as `disabled()` from the core library.

Created pull request #43

**Comment by ivanceras** [comment]
@deathbreakfast  Thank you for reporting this. The `node!` macro syntax and the "functional view calls"  syntax to build the views has a slight difference call branch. 

The `node!` macro syntax is building the Attribute based on the attribute name and the value provided in the html-like syntax.
However, in the "functional view calls" the attribute functions is using a hand-written function calls which mitigates the unintuitive behavior of the browser where it is only checking the presence of the attribute instead of evaluating if the set value is false.

[`disabled`](https://github.com/ivanceras/sauron/blob/644e78eaeb39d21aba4f5f2de138ab2167e2c090/crates/sauron-core/src/html/attributes.rs#L286),
```rust
pub fn disabled<MSG>(is_disabled: bool) -> Attribute<MSG> {
    if is_disabled {
        attr("disabled", true)
    } else {
        empty_attr()
    }
}
```
You  can still use this attribute function in the node macro syntax like this:
```html
use sauron::html::attributes::disabled;

<input class="prev_page" type="button"
{disabled(self.page <= 1)}
 value="<< Prev Page"
 on_click=|_| {
     trace!("Button is clicked");
     Msg::PrevPage
 }
/>
```
However, this is also non-intuitive and provides an inconsistent behavior on a 2 different way of writing code.
The needed fix would be in the same manner as the [`checked`](https://github.com/ivanceras/sauron/blob/644e78eaeb39d21aba4f5f2de138ab2167e2c090/crates/sauron-core/src/dom/created_node.rs#L273)  attribute.

**Comment by ivanceras** [comment]
I've now added the `fetch-data-macro-syntax` to make this work on the `node!` macro syntax.

**Comment by ivanceras** [comment]
A new version of sauron (0.43.8) has been published to [`crates.io`](https://crates.io/crates/sauron) containing the fix for this issue.
