### ISSUE TITLE
nodes inserted at position 0 have broken events

### ISSUE THREAD

**Issue by vwpix** [ivanceras/sauron#47]
the new closures created at view() don't get passed to the corresponding elements
instead, every new node acts like the original first node, or panic on keyed nodes

i made an example code for this problem, also a video preview to illustrate it better
```rust
use {
    sauron::{
        html::text,
        prelude::*,
        Cmd, Application, Node, Program,
    },
};

struct Container {
    nodes: Vec<u32>,
    last: String
}
enum Msg {
    InsertNode,
    AddNode,
    ClickNode(u32)
}

impl Application<Msg> for Container {
    fn view(&self) -> Node<Msg> {
        let buttons = self.nodes.iter()
            .map(|&x|button([on_click(move |_|Msg::ClickNode(x))],[text(x)])).collect::<Vec<_>>();
        div([],[
            text(&self.last),
            button([on_click(|_|Msg::InsertNode)],[text("add item (broken)")]),
            button([on_click(|_|Msg::AddNode)],[text("add item (working)")]),
            div([id("buttons")],buttons)
        ])
    }
    fn update(&mut self, msg: Msg) -> Cmd<Self, Msg> {
        match msg {
            Msg::InsertNode => self.nodes.insert(0,self.nodes.len() as u32),
            Msg::AddNode => self.nodes.push(self.nodes.len() as u32),
            Msg::ClickNode(pos) => self.last = pos.to_string()
        }
        Cmd::none()
    }
}

#[wasm_bindgen(start)]
pub fn main() {
    Program::mount_to_body(
        Container{
            nodes: vec![], 
            last: String::default()
        }
    );
}
```
[video preview](https://user-images.githubusercontent.com/94201379/141558549-8cb84020-864c-44e8-8546-ff65a1225061.mp4)
only tested this for position 0 so im not sure about the rest

**Comment by ivanceras** [comment]
Thank you @vwpix for a very detailed report on the issue. We will be working on this.

**Comment by ivanceras** [comment]
So, after some fiddling I realize that this is one of the case where the DOM diffing fails.
The code which deals with diffing elements in the DOM by comparing their attributes and event listener to see if the element can be reused or not. In rust, 2 closures are not equal even if they have the same exact code. This is not suitable for the dom-diffing algorithm as we want to be able to re-use the elements as much as possible otherwise, it will re-create the element for each view call which would makes the whole system very sluggish. 
That said, we try to [compare](https://github.com/ivanceras/sauron/blob/39241460a7313f30f714ec5d00b6e12853ba91ba/crates/sauron-core/src/html/attributes/listener.rs#L120) closures based only on their function signatures, in order to aggressively match old elements to new elements as much as possible.

This will be the behavior of the framework for now, while I haven't found a better way to solution. For now, you can use the work around to mark the element with `replace(true)` which instruct the diffing algorithm to re-create the element at every view call.



```rust
        let buttons = self
            .nodes
            .iter()
            .map(|&x| {
                button(
                    [
                        id(format!("btn_{}", x)),
                        replace(true),
                        on_click(move |_| Msg::ClickNode(x)),
                    ],
                    [text(x)],
                )
            })
            .collect::<Vec<_>>();
```

**Comment by ivanceras** [comment]
Also, I couldn't re-create the crash error: `closure invoked recursively` in any browser: firefox,chrome,webkit. I'm on linux.

Hint: you can rewrite your view like this to make it cleaner.

```rust 
   fn view(&self) -> Node<Msg> {
        div(
            [],
            [
                text(&self.last),
                button(
                    [on_click(|_| Msg::InsertNode)],
                    [text("add item (broken)")],
                ),
                button(
                    [on_click(|_| Msg::AddNode)],
                    [text("add item (working)")],
                ),
                div(
                    [id("buttons")],
                    self.nodes.iter().map(|&x| {
                        button(
                            [
                                id(format!("btn_{}", x)),
                                replace(true),
                                on_click(move |_| Msg::ClickNode(x)),
                            ],
                            [text(x)],
                        )
                    }),
                ),
            ],
        )
    }
```

**Comment by vwpix** [comment]
thank u for looking into it, and the workaround tip will be useful for now
> Also, I couldn't re-create the crash error: `closure invoked recursively` in any browser: firefox,chrome,webkit. I'm on linux.
the crash show up if i add the "key(x)" attribute to the generated buttons , tested in latest firefox nightly and chromium

**Comment by ivanceras** [comment]
After hours of hard-work revising and improving the [diffing algorithm](https://github.com/ivanceras/mt-dom/commit/941f462a71a4fa62c891c9c588893a7c181eb510) for keyed elements and tracking down the [bug](https://github.com/ivanceras/sauron/commit/b66483e433296295ddb8b26c11a5091f658424ce) for the  `closure invoked recursively or destroyed already` error, this issue is now solved.

I created a [repo](https://github.com/ivanceras/issues-sauron) for issues like this, which contain the actual code for the use-case.

Thank you @vwpix again, for filing this issue, this has solved multiple long-standing bug in `sauron` and in [`mt-dom`](https://github.com/ivanceras/mt-dom) code.

**Comment by ivanceras** [comment]
crate version where this is fixed:
- sauron 0.49.2
- mt-dom 0.19.0
